### PR TITLE
More readable empty strings

### PR DESCRIPTION
**Pull request by hindermath**
With the String helper String.Empty this this is a more readable variant of a hard-coded empty string with `''`.

### CODE REVIEW

**Comment by holgerflick** [comment]
This is more personal preference. I would never initialize with `.Empty`. Honestly, I never even thought it was an option. (You learn something new every day). Is there any advantage other than optical?

Also introducing constants is what I do in a real-world project, but it makes the example code less readable for the book and video audience. 

My current vote would be to not merge this into the source for everybody. I will not close though in case you have arguments that I am not aware of.

**Comment by hindermath** [comment]
" but it makes the example code less readable for the book and video audience." I am not aware of this topic. So do not merge this into your Code. In my example app in my Github repo I implemented the Code in this way.

**Comment by hindermath** [comment]
" but it makes the example code less readable for the book and video audience." I am not aware of this topic. So do not merge this into your Code. In my example app in my Github repo I implemented the Code in this way.

**Comment by holgerflick** [comment]
Agreed by both parties that the suggestion is valid but not "easier" for example/demo code used in books/videos.

**Pull request closed without merging**
